# Generated by Django 6.0 on 2026-01-16 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulos',
            name='descricao',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='modulos',
            name='link',
            field=models.URLField(),
        ),
    ]
